name: EconomyPlugin
version: '${project.version}'
main: dev.manere.economy.EconomyAPIPlugin
authors: [Manere_]
description: Simple EconomyPlugin plugin you can integrate in your own plugins.
website: https://github.com/Manered/Economy
softdepend: [PlaceholderAPI]

permissions:
  economy.balance:
    default: true
    description: Allows use of command '/balance'

commands:
  balance:
    description: Shows the balance of a player.
    permission: economy.balance
    aliases:
      - bal
      - playerbalance